spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
         uri: https://gitee.com/fox_hu/config-repo.git
         username: hwq8910@163.com
         password: fox6228676
#         basedir: E:\project\SrpringCloud_Sell_Distributed\config\basedir
         basedir: /Users/Macx/MyDocuments/SrpringCloud_Sell_Distributed/config/basedir
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh